# Python for Data Analytics

 - Numpy 
 - Pandas 
 - Matplotlib /Seaborn
 - Power Bi
 - Statistics
 - Predictive Analytics (ML )

# Numpy

 - Numerical Python: 
                    - its an array written in C
 
                    - Fast 
                     
                    -  Vectorised Operation    

### Array Creation
       - python list
       - array()
       - arange()
       

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [5]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
# array size
arr.size

10

In [8]:
# array shape
arr.shape

(10,)

In [9]:
arr.ndim

1

In [10]:
arr[4]

5

In [11]:
arr[3:7]

array([4, 5, 6, 7])

In [12]:
arr[9:3:-1]

array([10,  9,  8,  7,  6,  5])

# 2D-aRRAY

In [32]:
arr2d = np.array([
                   [1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12],
                   [11,22,33,44]
                 ])

In [33]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [11, 22, 33, 44]])

In [34]:
arr2d.size

16

In [35]:
arr2d.shape

(4, 4)

In [36]:
arr2d.ndim

2

In [37]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [11, 22, 33, 44]])

In [38]:
arr2d[2][2]

11

In [39]:
arr2d[2,2]

11

# Indexing and Slicing

In [49]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [11, 22, 33, 44]])

In [54]:
arr2d = np.arange(64).reshape(8,8)
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [55]:
# indexing
arr2d[3:6,5:7]

array([[29, 30],
       [37, 38],
       [45, 46]])

In [51]:
arr2d[2,0]

9

In [52]:
arr2d[3,3]

44

In [42]:
#[r,c]>>> [startrow:endrow   , startcol:endcol]
arr2d[]

array([[6]])

In [43]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [11, 22, 33, 44]])

In [44]:
arr2d[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [46]:
arr2d[2:3,1:3]

array([[10, 11]])

In [48]:
arr2d[:,3:]

array([[ 4],
       [ 8],
       [12],
       [44]])

In [56]:
arr2d[3:6,2:6]

array([[26, 27, 28, 29],
       [34, 35, 36, 37],
       [42, 43, 44, 45]])

In [57]:
arr2d[1:,4:6]

array([[12, 13],
       [20, 21],
       [28, 29],
       [36, 37],
       [44, 45],
       [52, 53],
       [60, 61]])

In [58]:
arr2d[:,1:7]

array([[ 1,  2,  3,  4,  5,  6],
       [ 9, 10, 11, 12, 13, 14],
       [17, 18, 19, 20, 21, 22],
       [25, 26, 27, 28, 29, 30],
       [33, 34, 35, 36, 37, 38],
       [41, 42, 43, 44, 45, 46],
       [49, 50, 51, 52, 53, 54],
       [57, 58, 59, 60, 61, 62]])

In [61]:
arr2d[4:5,3:5]

array([[35, 36]])

In [62]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [63]:
arr2d[2,4] = 200

In [64]:
arr2d

array([[  0,   1,   2,   3,   4,   5,   6,   7],
       [  8,   9,  10,  11,  12,  13,  14,  15],
       [ 16,  17,  18,  19, 200,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29,  30,  31],
       [ 32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47],
       [ 48,  49,  50,  51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60,  61,  62,  63]])

In [67]:
a=arr2d[2,4]

In [68]:
type(a)

numpy.int32

# array 3d

In [74]:
arr3d = np.arange(24).reshape(2,4,3) # (depth, row, col)
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [75]:
arr3d.ndim

3

In [76]:
arr3d[1,1,1]

16

In [77]:
arr3d[1,2,2]

20

# Vectorized Operation:

In [78]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
lst=[]
for a in arr:
    lst.append(a*10)

In [80]:
lst

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

In [81]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
arr*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [83]:
arr2d

array([[  0,   1,   2,   3,   4,   5,   6,   7],
       [  8,   9,  10,  11,  12,  13,  14,  15],
       [ 16,  17,  18,  19, 200,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29,  30,  31],
       [ 32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47],
       [ 48,  49,  50,  51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60,  61,  62,  63]])

In [84]:
arr2d/10

array([[ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7],
       [ 0.8,  0.9,  1. ,  1.1,  1.2,  1.3,  1.4,  1.5],
       [ 1.6,  1.7,  1.8,  1.9, 20. ,  2.1,  2.2,  2.3],
       [ 2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1],
       [ 3.2,  3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9],
       [ 4. ,  4.1,  4.2,  4.3,  4.4,  4.5,  4.6,  4.7],
       [ 4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,  5.5],
       [ 5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3]])